//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_1116.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindPet
    {
        public int PetID { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string LostDate { get; set; }
        public string LostPlace { get; set; }
        public string PetPhoto { get; set; }
    }
}
